irecovery -f boot/iBSS.img4
irecovery -f boot/iBEC.img4
irecovery -c go
irecovery -f boot/devicetree.img4
irecovery -c devicetree
irecovery -f boot/trustcache.img4
irecovery -c firmware
irecovery -f boot/krnlboot.img4
irecovery -c bootx
